#!/bin/sh

[ -z $install_source ] && install_source=$(pwd)

[ -f $install_source/install ] || {
    echo No installation source.
    exit -1
}

git submodule init
git submodule update

mkdir -p ~/.vim
mkdir -p ~/.config/nvim

for f in $install_source/nvim/*; do
	bf=$(basename $f)
	ln -sfn $f ~/.vim/$bf
	ln -sfn $f ~/.config/nvim/$bf
done
ln -sfn $install_source/nvim/init.vim ~/.vimrc

[ -d ~/.vim/bundle/Vundle.vim ] || {
  mkdir -p ~/.vim/bundle
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
}
[ -d ~/.config/nvim/bundle/Vundle.vim ] || {
  mkdir -p ~/.config/nvim/bundle
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.config/nvim/bundle/Vundle.vim
}

ln -sfn $install_source/gitconfig ~/.gitconfig
ln -sfn $install_source/ptconfig.toml ~/.ptconfig.toml

ln -sfn $install_source/xresources ~/.Xresources

ln -sfn $install_source/zsh ~/.zsh
ln -sfn $install_source/zsh/zshrc ~/.zshrc
ln -sfn $install_source/bin ~/bin

ln -sfn $install_source/gitconfig ~/.gitconfig

test -d ~/.ncmpc || mkdir ~/.ncmpc
ln -sfn $install_source/ncmpc_config ~/.ncmpc/config

ln -sfn $install_source/tmux.conf ~/.tmux.conf
ln -sfn $install_source/mpv ~/.config/mpv


mkdir -p ~/node/modules
ln -sfn $install_source/npmrc ~/.npmrc
