#!/bin/sh

[ -z $install_source ] && install_source=$(pwd)

[ -f $install_source/install ] || {
    echo No installation source.
    exit -1
}

git submodule init
git submodule update

ln -sfn $install_source/vim ~/.vim
ln -sfn $install_source/vim/vimrc ~/.vimrc

ln -sfn $install_source/zsh ~/.zsh
ln -sfn $install_source/zsh/zshrc ~/.zshrc
ln -sfn $install_source/bin ~/bin

ln -sfn $install_source/gitconfig ~/.gitconfig

test -d ~/.ncmpc || mkdir ~/.ncmpc
ln -sfn $install_source/ncmpc_config ~/.ncmpc/config

ln -sfn $install_source/tmux.conf ~/.tmux.conf
