#!/bin/sh

pwd=$(readlink -f $(dirname $0))
#echo $pwd

mkdir -p ~/.vim
ln -sfn $pwd/init.vi ~/.vimrc



mkdir -p ~/.config/nvim

for f in $pwd/*.vim $pwd/after $pwd/colors $pwd/snippets $pwd/templates; do
	bf=$(basename $f)
	ln -sfn $f ~/.config/nvim/$bf
done

[ -f ~/.config/nvim/autoload/plug.vim ] || {
  mkdir -p ~/.vim/autoload
  curl --create-dirs \
    --location \
    --output ~/.config/nvim/autoload/plug.vim \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

