#!/bin/sh

export MOZ_ENABLE_WAYLAND=1
export XDG_CURRENT_DESKTOP=Unity
export QT_QPA_PLATFORM=wayland
export QT_QPA_PLATFORMTHEME=qt5ct
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland

pkill dbus
eval $(dbus-launch --sh-syntax 2>&1 | tee -a /tmp/dbus-launch.log)
#dbus-update-activation-environment --systemd --all
exec ssh-agent /usr/bin/sway 2> ~/sway.stderr.log | tee ~/sway.stdout.log
