#!/usr/bin/env zsh

#
# !!! common aliases
#

alias ack='clear; ack'
alias grep="grep --color=auto -d skip"
alias ssh='TERM=xterm ssh -C'

alias edzsh='vim ~/.zsh/zshrc; . ~/.zsh/zshrc'
alias edalias='vim ~/.zsh/aliases; . ~/.zsh/aliases'
alias edalias.priv='vim ~/.zsh/aliases.private; . ~/.zsh/aliases.private'

alias edbash="vim ~/.bashrc && source ~/.bashrc"

alias mj="make -j3 -s"
alias mi="sudo make install -j3 -s"

alias rdesktop='rdesktop -xb -z -a16 -rsound:off -r clipboard:PRIMARYCLIPBOARD -0 -g1200x900'

if [[ `uname` == "SunOS"  ]] {
    #
    # Solaris
    #

    # use gnu ls if it is available, even if not in PATH
    # (nice to have in jucr build environment)
    if [[ -f '/usr/gnu/bin/ls' ]] {
        LS=/usr/gnu/bin/ls
        alias l="$LS -lh --color=tty"
        alias ll="$LS -lAh --color=tty"
        alias ls="$LS --color=tty"
    } else {
        # stock ls is oldskool unixey ls
        unalias ls
        alias l='ls -lh'
        alias ll='ls -lAh'
    }


    alias spause='pfexec svcadm disable -t'
    alias sstop='pfexec svcadm disable'
    alias sstart='pfexec svcadm enable'
    alias srestart='pfexec svcadm restart'

    alias pvim='pfexec vim'


    alias psql='psql -U esports'
    alias rsql='rlwrap psql -U esports'
    alias ccl='rlwrap ccl'

    alias isthere='pfexec pkg list -a | grep -i'
    alias current='pfexec pkg list | grep -i'
    alias drop='pfexec pkg uninstall'
    alias canhaz='pfexec pkg install --no-refresh '
    alias inside='pfexec pkg contents'

    alias p='ps -ef'
    alias pss="ps -ef | grep -i"

    alias iddqd='pfexec zsh'
    alias pkg='pfexec pkg'

    # solaris ping is dumb
    alias ping='ping -s'

    if [[ -f /usr/gnu/bin/grep ]] {
        true
    } else {
        unalias grep
    }


} else {
    #
    # Mostly archlinux-specific
    #
    alias l='ls -lh --color=tty --si'
    alias ll='ls -lAh --color=tty --si'
    alias ls='ls --color=tty --si'

    # http://www.reddit.com/r/linux/comments/8pmss/alias_iddqdsudo_su/
    alias canhaz='sudo $PACMAN_CMD -S --needed'
    alias drop='sudo $PACMAN_CMD -R'
    alias isthere='sudo $PACMAN_CMD -Ss'
    alias current='$PACMAN_CMD -Q | grep '

    #alias inside='pacman -Ql'

    function inside { $PACMAN_CMD -Ql $1 | grep -v '/$' }
    function binside { $PACMAN_CMD -Ql $1 | grep -v '/$' | grep --color=never bin }

    alias whohas='$PACMAN_CMD -Qo'
    alias whose='$PACMAN_CMD -Qo'
    alias y='yaourt'

    alias iddqd='sudo -i'

    alias relight='sudo /etc/rc.d/lighttpd restart'

    alias pss="ps -Adf | grep -i"
    alias p="/bin/ps axfwwh -eo '%p %U %a'"
    alias S='sudo'

}
alias tree="ls -R | grep ':$' | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'"

# git
alias gitd="git diff"
alias gitdc="git diff --cached"
alias gits="git status"
alias gitc="git commit"
alias gitsc="test -d .git/svn && git svn dcommit"
alias master="git checkout master"

# svn

alias sc="svn commit"
alias scc="svn commit -m turbocommit"
alias sd="svn diff -x -w"
alias ss="svn stat --ignore-externals"
alias sa="svn add"
alias suu="svn update --ignore-externals"

alias c="cd ~/.wine/drive_c/"
alias ppp="cd ~/.wine/drive_c/Program\ Files/"
alias pppp="cd ~/.wine/drive_c/Program\ Files/Games"

alias offlineimap='offlineimap -u Noninteractive.Basic'
alias oi="offlineimap -u Noninteractive.Basic 2>/dev/null | grep --line-buffered 'message\|account'| grep --line-buffered -v 'Adding flags'"

alias xsel='xsel -b'

alias xc='xcalib ~/Samsung*.icm'

alias rsynx='rsync -vax --no-owner --no-group --no-perms'

#alias phptags="find . -name '*.php' | grep -v deployment | xargs ctags"
alias phptags="ctags **/*.php"

alias py=ipython

alias suy='clear; S $PACMAN_CMD -Suy'
alias syu='clear; S $PACMAN_CMD -Suy'

alias du='du --si'
alias df='df --si'

# pss virtualbox | KILL
alias -g KILL=" awk '{print \$2}' | xargs /bin/kill "
alias -g KILL9=" awk '{print \$2}' | xargs /bin/kill -9 "




alias acka='ack --follow -a -i -Q'
alias ackj='ack --type=java -i -Q'
alias wget='wget -U "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)" --load-cookies=/tmp/wget.cookies.txt --save-cookies=/tmp/wget.cookies.txt --keep-session-cookies'

# rlwraps

alias mzscheme='rlwrap mzscheme'
alias scheme='rlwrap mzscheme'
alias ocaml='rlwrap ocaml'
alias ocamldebug='rlwrap ocamldebug'
alias sbcl='rlwrap sbcl'
alias arc='cd ~/arc; rlwrap mzscheme -m -f as.scm'
alias clojure='rlwrap java -cp $CLOJURE_HOME/clojure.jar clojure.lang.Repl'


alias cflagged='CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe" CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe" LDFLAGS="-Wl,--hash-style=gnu -Wl,--as-needed"'

alias mc='test $TERM = screen-256color -o $TERM = screen && TERM=xterm mc || mc'

alias m='clear; make -s'

alias clip='xclip -o -selection clipboard'
alias clipp='xclip -o -selection primary'

alias temps='sudo hddtemp /dev/sda; sudo hddtemp /dev/sdb; sudo hddtemp /dev/sdc'

# space as a delimiter for xargs is too idiotic
# also add -n 1 as a default, we're in no hurry
alias xargs="xargs --delimiter '\n' -n 1"

alias hexdump='od -Ax -tx1z -v'

# head/tail as many lines as possible w/o scroll
alias head='head -n $[$LINES-2]'
alias tail='tail -n $[$LINES-2]'

# show sizes of subfolders in current direcory
#alias dirsizes='\du --max-depth=1 | sort -nr | head -n 20'
function dirsizes {
    \du --max-depth=1 | sort -nr | head -n 30 | sed 's/^.*\t//' | xargs --delimiter=\\n -n 1 \du -sh
}


# vim: syn=zsh :
