#!/usr/bin/env zsh

case `uname` in
    Linux)

        source ~/.zsh/aliases.linux

        cat /etc/issue | grep Arch >/dev/null
        if [[ $? == 0 ]]; then
            source ~/.zsh/aliases.linux.archlinux
        fi

        cat /etc/issue | grep Ubuntu >/dev/null
        if [[ $? == 0 ]]; then
            source ~/.zsh/aliases.linux.ubuntu
        fi

        ;;

    SunOS)

        source ~/.zsh/aliases.solaris

        ;;

esac


if [[ -f ~/.zsh/aliases.private ]]; then

    source ~/.zsh/aliases.private

fi

