#!/usr/bin/env zsh

case $(uname) in
    Linux)

        try_source ~/.zsh/aliases.linux

        cat /etc/issue | grep Arch >/dev/null
        if [[ $? == 0 ]]; then
            try_source ~/.zsh/aliases.linux.archlinux
        fi

        cat /etc/issue | grep Ubuntu >/dev/null
        if [[ $? == 0 ]]; then
            try_source ~/.zsh/aliases.linux.ubuntu
        fi

        ;;

esac


try_source ~/.zsh/aliases.private

